#!/usr/bin/python3
#This script removes known germline mutations from a helmsman "simple text" format file, using a germline "simple text" file, as generated by filter_somatic.py

import argparse

def argparser():
    parser = argparse.ArgumentParser()
    parser.add_argument('-g', '--germline', help = 'Filename for germline mutation output', default = 'germline.vcf')
    parser.add_argument('-i', '--input', help = 'Filename to strip germlines out')
    args = parser.parse_args()
    return args

def iterator(inp, ger):
    germs = parse_text(ger)
    data = parse_text(inp)
    for key, entry in sorted(data.items()):
        if key not in germs:
            print(entry)

def parse_text(infile):
    body = {}
    with open(infile) as inf:
        for entry in inf:
            spent = entry.strip().split()
            body[(spent[0],spent[1],spent[3])] = entry.strip()
    return body

def main():
    args = argparser()
    iterator(args.input, args.germline)

if __name__ == '__main__':
    main()